### ISSUE TITLE
Fully-accelerated HEVC main10 decoding is not eabled in master branch

### ISSUE THREAD

**Issue by uniemimu** [intel/gstreamer-media-SDK#170]
branch topic_linux_and_windows supposedly supports hw accelerated HEVC 10-bit decoding. Why don't master branch?

Currently master-branch skips the search for the hw plugin, and if the sw decoder is missing, master branch fails with a segfault if HEVC 10-bit-decoding is attempted. That is, if the plugin with hash 15dd936825ad475ea34e35f3f54217a6 is not found, end result is a crash:

Caught SIGSEGV
#0 0x00007fb6d4ab0bf9 in __GI___poll (fds=0x55e4fb0af420, nfds=2, timeout=-1)
#1 0x00007fb6d4ff8539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2 0x00007fb6d4ff88d2 in g_main_loop_run ()
#3 0x00007fb6d555b8b3 in gst_bus_poll ()
#4 0x000055e4fa3e0bb3 in ?? ()
#5 0x000055e4fa3dfc0e in ?? ()
#6 0x00007fb6d49bdb97 in __libc_start_main (main=0x55e4fa3df460, argc=17, 
#7 0x000055e4fa3e00da in ?? ()

**Comment by uniemimu** [comment]
ref https://github.com/intel/gstreamer-media-SDK/issues/49
